### ISSUE TITLE
Work on making WebUI faster to load.

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#147]
When lots of results are available, the WebUI can be slow to load.  We should think about ways of improving this.  Also it can be nice to see results trickle in without having to reload the page, so it might be good to have a facility to avoid refreshes.

**Comment by hevrard** [comment]
Performance:
It is mainly slow because it has to parse all .info.json files.
We already have a trick to cache this information, and parse again the files only if they are more recent than the last time we parsed them. So you can "warm up" the webui, re-loading a page with many results should get you the page much faster.

Next step to get faster is to load everything in a database, that's what the CTS does, but it adds much more complexity.

Dynamic pages:
Yes in principle, non-trivial to do in practice.
We can also lazy-load the images as they appear on screen, that would speed up page renderings.
This is all asynchronous javascript stuff. I do *not* volunteer to do this :)

Possible solutions:
- keep on patching our WebUI
- Have the webui revamped by someone who knows how to do such things properly
- Reuse somehow what the dEQP folks did with Cherry

**Comment by paulthomson** [comment]
Obsolete
