### ISSUE TITLE
Allow random generation of reference input data in generated shader job

### ISSUE THREAD

**Issue by abelbriggs1** [google/graphicsfuzz#450]
Currently, when generating a family of variants for a shader, the generator simply copies the original shader job JSON into the new directory and uses it to create the variant JSON files, like so:

bubblesort_flag.json
`{
    "injectionSwitch": {
        "func":  "glUniform2f",
        "args": [
            0.0,
            1.0
        ]
    },
    "resolution": {
        "func":  "glUniform2f",
        "args": [
            256.0,
            256.0
        ]
    }
}`

reference.json
`{
  "injectionSwitch": {
    "func": "glUniform2f",
    "args": [
      0.0,
      1.0
    ]
  },
  "resolution": {
    "func": "glUniform2f",
    "args": [
      256.0,
      256.0
    ]
  }
}`

This means that no matter how many variants you generate, the input uniforms will never change unless you use a different original JSON file. This is great in most cases, but some shaders/algorithms could have special cases depending on the input values that could result in different behavior. Covering the different behaviors of a shader and its variants with different inputs would increase the possibility of finding compiler bugs.

It would be nice to be able to tell the generator to randomize some inputs in our JSON file while preparing it as a reference job. For example, a string that would tell the type of random value and its upper bound.

Perhaps something like this: (notice the first data field)

comp-0003-random-middle-square.json
`{
  "$compute": {
    "num_groups": [ 2, 1, 1 ],
    "buffer": {
      "binding": 0,
      "fields":
      [
        { "type": "int", "data": [ "randint(12345)" ] },
        { "type": "int", "data":
          [ 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0
          ]
        }
      ]
    }
  }
}`

reference.json
`{
  "$compute": {
    "num_groups": [ 2, 1, 1 ],
    "buffer": {
      "binding": 0,
      "fields":
      [
        { "type": "int", "data": [ 7890 ] },
        { "type": "int", "data":
          [ 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0
          ]
        }
      ]
    }
  }
}`

All variants of a given shader family would have the same inputs. Generating another family with a different seed would give you a different family of variants with a different set of random inputs. The input generation would use the same seed as the variant generator, so you'd still get the same set of variant shaders for a given JSON file.

This would probably be most useful for compute shaders, which often work with integers. Trying to randomize something like "resolution" in bubblesort_flag (a floating point value meant to be a natural number) would probably go horribly wrong - I assume it'd be up to the user to vet which uniforms they'd use this for.

**Comment by afd** [comment]
Hi Abel

Sorry for the delay in responding to this - I've been away.

I really like the overall idea of amplifying a reference shader job into multiple reference shader jobs that differ according to their uniforms - I'm pleased that you have proposed this and am keen to support you in getting it in to the tool.

I propose that we take a slightly different approach though.

If we already had several references that were identical except that their .json files had different uniform values, we could run glsl-generate on them with no further effort.

So rather than adapting glsl-generate so that it knows how to understand an extended JSON format with the extensions that you propose, I think it would be better to write a separate tool for preprocessing a shader-job-with-random-parameters (let's call this a "parameterized" shader job) into several normal shader jobs.  Afterwards, glsl-generate could be invoked directly on the resulting shader jobs.

I believe this would avoid increasing the complexity of glsl-generate (and in particular it would resolve one of the questions you raised in #455).

I also have some thoughts about how to represent the random values in the JSON, but I need to think more on it, so let's revisit once we've discussed the overall design a bit more here.

**Comment by abelbriggs1** [comment]
Thanks for the feedback, I know you've been out/busy the past week or so. The PR was mostly for exploration of ideas - by the time I hit the issue with Vulkan binding generation, I had already figured that I was taking the wrong approach, but I wanted to make sure and get feedback on it anyway.

By a separate tool, you mean a new folder/.jar file in `/graphicsfuzz/target/graphicsfuzz` with a corresponding Python script to run the tool from the terminal?

If that's the case, it might be better to change the scope a little bit - instead of taking an already-created job file and trying to randomize uniform values using arbitrary strings, it might be better to take a shader, parse it for inputs/uniforms/bindings and produce a shader job file from it with the randomized values. That would have the added benefit of allowing users to create jobs automatically for any given shader, without having to hand-write JSON. This would, however, lead to a case where users may have to go into the JSON to set certain variables that need to be specific(like `resolution` in `bubblesort_flag.frag`, which needs to be a natural number). But ultimately I think that would be more universally useful than parsing an already-made job file.

**Comment by abelbriggs1** [comment]
For this, it would probably be better to develop a Python script as well as a way of specifying how to generate the JSON file. I'll close for now - reopen if there's interest in such a tool in the future.
