### ISSUE TITLE
Reducer: injected code is not completely removed in the reduced final shader

### ISSUE THREAD

**Issue by jiradeto** [google/graphicsfuzz#568]
When running a reduction, all injected code in the reduced final shader `variant_XXX_reduced_final.frag` is supposed to be removed. 

However, when running a reduction with preserve semantics and the shader being reduced crashes, a reducer does not remove some fragment of the injected code, leaving the injected `_GLF_XXX` persists in the reduced final shader.

The result of the reduction ([reductions.zip](https://github.com/google/graphicsfuzz/files/3303141/reductions.zip)) is attached for further investigation.

Client.json
```JSON
{
  "platform_info": {
    "clientplatform": "desktop",
    "http.agent": "",
    "java.class.version": "52.0",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_202-b08",
    "java.vendor": "Oracle Corporation",
    "java.version": "1.8.0_202",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.specification.vendor": "Oracle Corporation",
    "java.vm.specification.name": "Java Virtual Machine Specification",
    "java.vm.vendor": "Oracle Corporation",
    "java.vm.vendor.url": "",
    "java.vm.version": "25.202-b08",
    "java.specification.name": "Java Platform API Specification",
    "java.specification.vendor": "Oracle Corporation",
    "java.specification.version": "1.8",
    "os.arch": "amd64",
    "os.name": "Linux",
    "os.version": "4.18.0-20-generic",
    "sun.cpu.endian": "little",
    "sun.io.unicode.encoding": "UnicodeLittle",
    "sun.desktop": "gnome",
    "sun.java.launcher": "SUN_STANDARD",
    "sun.cpu.isalist": "",
    "sun.os.patch.level": "unknown",
    "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
    "sun.arch.data.model": "64",
    "user.region": "",
    "user.language": "en",
    "GL_VERSION": "3.0 Mesa 19.2.0-devel (git-88eb2a1f7e)",
    "GL_SHADING_LANGUAGE_VERSION": "1.30",
    "GL_VENDOR": "Intel Open Source Technology Center",
    "GL_RENDERER": "Mesa DRI Intel(R) Sandybridge Mobile ",
    "GL_MAJOR_VERSION": 3,
    "GL_MINOR_VERSION": 0,
    "Supported_GLSL_versions": []
  }
}
```

**Comment by afd** [comment]
I expect this was due to the crash occurring nondeterministically.  As a final step, the reducer simplifies a shader by replacing macros with their bodies.  If this leads to an uninteresting shader, the version with macros becomes the final version (just in case the macros were really required for the bug to trigger, which is possible).  If the shader is nondeterministically interesting, it may just happen that it is deemed uninteresting when the final test is performed, so that it looks like the macros are required when really they are not.

I checked this shader, and Simplifier does manage to remove all of the macros, hence why I expect it is due to nondeterminism.

Closing for now; please reopen if you are affected by the issue again and you believe it is not due to nondeterminism.
