### ISSUE TITLE
Add support to gfauto for generating wrong image CTS patches

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#658]
The gfauto tool, which is currently in [this branch](https://github.com/google/graphicsfuzz/tree/gfauto) (due to be merged soon) supports continuous fuzzing using GraphicsFuzz to find crash bugs, de-duplicate them, and transform unique crash bugs into patches that are nearly ready to be added to CTS (requiring a small amount of manual triage).

We would like an analogous flow for wrong image bugs, where GraphicsFuzz identifies a pair of equivalent shaders that lead to radically different images being rendered (due to a shader compiler bug).  We would like to be able to de-duplicate such issues and, for a unique wrong image bug generate a CTS patch.

The focus of this issue is on the second thing: generating a CTS patch.

Specifically, having found a pair of shaders, shader1 and shader2, that are equivalent but are found to expose a wrong image bug, we want to be able to obtain an Amber file that:

- Creates to graphics pipelines, pipeline1 and pipeline2 that use shader1 and shader 2, respectively
- Runs both pipelines
- Asserts that the resulting framebuffers are similar according to a fuzzy diff metric

Amber provides support for running multiple pipelines, and has a root mean square error diff facility thanks to [this PR](https://github.com/google/amber/pull/602).

**Comment by paulthomson** [comment]
Parts to this issue:

- [x] Code for generating AmberScript with multiple pipelines. Done in #705
- [ ] Code for easily converting a gfauto-style "source directory" to an AmberScript file.

**Comment by paulthomson** [comment]
See private repo: `examples/swiftshader_wrong_image`

Some notes:

We just want to pass the "source directory", instead of having to pass the test.json and shader paths. See the comments in fuzz.py for an attempt to "name" certain files and directories. E.g. the "source directory" contains the test.json file and directories for the variant and reference. `test_util.py` is attempt to add functions to find these files/directories, but could be improved. We could even consider adding some light-weight classes instead. E.g. `TestDir`, `SourceDir`, etc.
But also, feel free to just hard-code `source_dir / test_util.TEST_METADATA` and
`source_dir / test_util.VARIANT_DIR / test_util.SHADER_JOB`, etc., as we can refactor these later, if we really want to.

You probably want to extract all code from `tool.glsl_shader_job_to_amber_script` into a new function, except for the final `amberfy(` call. The new function just takes a GLSL shader job or a SPIR-V shader job and produces a SPIR-V ASM shader job into a hard-coded location in some work directory (and returns it). Then you can write a new function that takes several shader jobs and produces one AmberScript test. The existing `tool.glsl_shader_job_to_amber_script` function can keep its current behavior for now, so we can continue fuzzing for crashes.

**Comment by asuonpaa** [comment]
@paulthomson You mentioned three pipelines. What is the third one besides the reference and the variant?

**Comment by paulthomson** [comment]
The third pipeline is another variant: `examples/swiftshader_wrong_image/reduced_glsl_with_variant_2/variant_2/`

You can assume it will be in `variant_2/`, next to the `test.json`.

In terms of where it comes from, it is, in fact, the last, failed reduction step. Thus, it is very similar to the reduced variant, but has one additional transformation removed, and this was not sufficient to reproduce the bug. In some cases, the size of the diff between variant_2 and the variant may be smaller than the difference between the reference and variant. Thus, somebody debugging the issue may prefer to compare the variant and variant_2.

**Comment by paulthomson** [comment]
We now want to add support for compute shaders. As with fragment shaders, the Amber test should run each compute shader and store each output to a separate buffer, and then compare the buffers. Note that the compute shaders all use an input/output buffer (the output will clobber the input buffer), but I don't think this will be an issue.

**Comment by asuonpaa** [comment]
Is there anything else to add to this task?

**Comment by paulthomson** [comment]
Fixed by PR #735 
Thanks!
